### ISSUE TITLE
Training on Visual Genome dataset

### ISSUE THREAD

**Issue by dneirfi** [yrcong/RelTR#11]
Hi. Thanks for sharing your nice work!

Do you have any pre-trained weights on full Visual genome dataset? (not split one)

Thanks.

**Comment by yrcong** [comment]
Unfortunately we didn't train it on the original VG. I think it's a bit noisy (many ambiguous classes). 

Instead, we trained on OpenImages

**Comment by dneirfi** [comment]
Thanks for replying!
