### ISSUE TITLE
Train and Test for custom images

### ISSUE THREAD

**Issue by Chenghao-Ding** [yrcong/RelTR#14]
How did you get the  annotations of Visual Genome (in COCO-format)? Do you have tools to process the original datasets? I want to use in my custom datasets(only pictures), I have seen the KaihuaTang/Scene-Graph-Benchmark.pytorch code ,but have no idea to process the my custom datasets for training and testing. Thanks very much!

**Comment by yrcong** [comment]
We adopt the VG annotations provided by Neural Motifs and convert them into COCO format with the pre-processing code.
More details please check #6

**Comment by Chenghao-Ding** [comment]
> We adopt the VG annotations provided by Neural Motifs and convert them into COCO format with the pre-processing code. More details please check #6

Thanks for your timely reply! I find another way to solve my problem that is two-stage way including objects detection and relationships detection. Although two parts are splitted, but for my experiment may have an effective result. Your works looks very nice , thanks for your good job.

**Comment by rebelmachina** [comment]
@Chenghao-Ding did you train on custom images from scratch or fine-tune? How did you fine-tune?

**Comment by trangiahuy8444** [comment]
+1 How did you fine-tune?
