### ISSUE TITLE
when will you release open image train / evaluation code?

### ISSUE THREAD

**Issue by long8v** [yrcong/RelTR#15]
I found training, evaluation code for Open Images is not well-established.
I am looking forward to see them from your repo! If you have reference code for open images evaluation, let me know. 😄

**Comment by yrcong** [comment]
The paper is still under review and we have revised a few things. We will release all the code when we get new feedback.
It may take 1-2 month.

**Comment by long8v** [comment]
Thanks for answering. Wish you a good luck!
