### ISSUE TITLE
The training and evaluation code for OpenImage dataste.

### ISSUE THREAD

**Issue by JacobYuan7** [yrcong/RelTR#19]
Hi,
many thanks for your great work and contribution. I find that the code for OpenImage dataset hasn't been released. Is it possible for you to give a timeline about when it will be made public?

**Comment by yrcong** [comment]
Hi,
thank you for your interest in our work. We have revised our work and it is now under review. Therefore there are some modifications. We will update our code including OpenImages probably in March.

**Comment by JacobYuan7** [comment]
> Hi, thank you for your interest in our work. We have revised our work and it is now under review. Therefore there are some modifications. We will update our code including OpenImages probably in March.

Many thanks for your reply! Then is it possible to let me know the base code you use to implement the evaluation code? (is it [this one](https://github.com/SHTUPLUS/PySGG)?)

**Comment by yrcong** [comment]
> > Hi, thank you for your interest in our work. We have revised our work and it is now under review. Therefore there are some modifications. We will update our code including OpenImages probably in March.
> 
> Many thanks for your reply! Then is it possible to let me know the base code you use to implement the evaluation code? (is it [this one](https://github.com/SHTUPLUS/PySGG)?)

**Comment by yrcong** [comment]
> Many thanks for your reply! Then is it possible to let me know the base code you use to implement the evaluation code? (is it [this one](https://github.com/SHTUPLUS/PySGG)?)

We use the common evaluation program (I guess it is written by MOTIFS..). The code is [attached](https://github.com/yrcong/RelTR/tree/main/lib/evaluation).
