### ISSUE TITLE
Regarding Pretrained Model Weights

### ISSUE THREAD

**Issue by hyzcn** [yrcong/RelTR#2]
Dear Author, thanks for your fabulous code! I have a question regarding model training, wondering if you initialized the model with pretrained detr model or you just train the whole network from scratch?

**Comment by yrcong** [comment]
I trained the whole network from scratch:)

**Comment by hyzcn** [comment]
By the way, will it take a lot time to converge. I tried to train on my data, but seems very slow. Wondering how many epoch typically need

**Comment by yrcong** [comment]
I remembered I have written in the paper. I trained 150 epochs with 8 RTX2080 (2 images per GPU).
