### ISSUE TITLE
Some details about Open Image v6.

### ISSUE THREAD

**Issue by JacobYuan7** [yrcong/RelTR#21]
Many thanks for the great work.
Since the code for Open Image v6 is not release, may I ask about the data split you use for training?
**Do you use the train+val splits or only train split for training?**

**Comment by JacobYuan7** [comment]
> Hi! Sorry for the late reply. We only use training images for the training.
> 
> But I guess there is no big difference between train+val and only train since the validation set is quite small.

Many thanks for your reply!
May I ask a follow-up question: is wmAP usually higher than mAP or lower? Would you mind giving some reasoning for this?

**Comment by yrcong** [comment]
I think wmAP should be higher usually. The models have better performance on the inference of high frequency relationships while these relationships have higher weights.

**Comment by JacobYuan7** [comment]
> I think wmAP should be higher usually. The models have better performance on the inference of high frequency relationships while these relationships have higher weights.

Sorry for the late reply. I agree with you. Many thanks for the information. I closed this issue as completed.
