### ISSUE TITLE
cannot start training

### ISSUE THREAD

**Issue by Turkishvein** [yrcong/RelTR#23]
cannot import functions betweeen py files

**Comment by yrcong** [comment]
?

**Comment by yrcong** [comment]
Could you give the error report? I cannot get the point.

**Comment by Turkishvein** [comment]
![image](https://user-images.githubusercontent.com/95733854/229410835-33c3fd96-4899-4d57-a537-1543a483df4b.png)

**Comment by Turkishvein** [comment]
hello, i reduced the error message to this: from datasets import build_dataset, get_coco_api_from_dataset in datasets folder there are no build_dataset neither get_coco_api_from_dataset py files. How can i get them?

**Comment by yrcong** [comment]
> hello, i reduced the error message to this: from datasets import build_dataset, get_coco_api_from_dataset in datasets folder there are no build_dataset neither get_coco_api_from_dataset py files. How can i get them?

Have you already installed pycocotools? I guess this is the reason.

**Comment by yrcong** [comment]
> i started train successfully, but this time gives that error after 2-3 hours later: File "main.py", line 191, in main train_stats = train_one_epoch(model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm) File "C:\Users\Uğur\Desktop\reltr\engine.py", line 61, in train_one_epoch torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm) File "C:\anaconda\envs\reltr\lib\site-packages\torch\nn\utils\clip_grad.py", line 38, in clip_grad_norm_ if clip_coef < 1: RuntimeError: CUDA error: unknown error thank you for solutions

It shows that something goes wrong during the gradient clipping. I have never seen this but it may be caused by the wrong cuda version.  Make sure that you are using pytorch==1.6.0 cudatoolkit=10.1. If you want to use RTX30 GPU, please use CUDA11.

**Comment by Turkishvein** [comment]
when install 
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=11 -c pytorch 
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
and train not starting :) i tried several pytorch versions and started train but interrupt likely in half of first epoch..

**Comment by yrcong** [comment]
I have never tried the code on Windows. For Linux/RTX3090/CUDA11.1/PyTorch1.10/, it works well.

**Comment by altansnl** [comment]
code works on windows fine. you just have a torch error instead of an error related to this repository. GL.
