### ISSUE TITLE
you commented out training code, training does not work at the moment

### ISSUE THREAD

**Issue by altansnl** [yrcong/RelTR#25]
https://github.com/yrcong/RelTR/commit/4d676ee5e3f8d01cd8a12648fdfb395dd6d17cdd

**Comment by yrcong** [comment]
Could you please give the error output?

**Comment by altansnl** [comment]
i do not have it at the moment, but you commented out the line we calls `train_one_epoch` in `main.py`

**Comment by Vincent-luo** [comment]
Yeah in the latest commit, in `main.py` lines including `train_one_epoch` are commented. So if I want to do training, all I have to do is to uncomment these lines?

**Comment by altansnl** [comment]
yeah you can uncomment and it works. i have been training a lot of RelTR.
