### ISSUE TITLE
demo问题

### ISSUE THREAD

**Issue by Zhangwt100** [yrcong/RelTR#27]
您好！请问在您提供的demo中如何更换其他图片呢？我更换的图片链接会报错。具体操作是什么呢？

**Comment by yrcong** [comment]
Do you mean the command?
```python inference.py --img_path $IMAGE_PATH --resume $MODEL_PATH```
Make sure your relative/absolute path is correct, and please report your error for more details.

**Comment by Zhangwt100** [comment]
> Do you mean the command? `python inference.py --img_path $IMAGE_PATH --resume $MODEL_PATH` Make sure your relative/absolute path is correct, and please report your error for more details.

我的意思是您提供的colab的demo

**Comment by yrcong** [comment]
Please make sure the link is available and check that the channel of the source image is not 4 (RGBA), which is expected to be 3 (RGB).
I tried some links, they work fine, for example:
 https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Yellow_Happy.jpg/1200px-Yellow_Happy.jpg
