### ISSUE TITLE
The problem of training time

### ISSUE THREAD

**Issue by Yassin-fan** [yrcong/RelTR#28]
Thanks for your inspiring work！
According to your report, the model was trained on 8 RTX2080 (2 images per GPU) for 150 epochs to reach the expected performance, which is a bit too long to modify/re-train based on the code.

Therefore, I would like to know if the model took so long to train because the DETR part was completely retrained? 
Is it possible to use the pre-trained DETR encoder part to reduce the training overhead?

**Comment by yrcong** [comment]
Hi,
I think it is reasonable but I am not sure if it really works. The decoder learns the triplet distribution, which is the key. Empirically it takes some time.

**Comment by altansnl** [comment]
i tried loading a pretrained **DETReg** model (which loads the backbone and encoder, not the decoder as it is different). It did not really work. 

However, my pretrained model was trained on **ImageNet** which is different than **Visual Genome** (subset of **COCO**). So maybe it would work loading a **DETR** trained on **COCO** instead.

you can also try to freeze or not freeze the weights you are loading.
