### ISSUE TITLE
evaluating RelTR on PredCLS/SGCLS

### ISSUE THREAD

**Issue by Ljy-an** [yrcong/RelTR#3]
Dear Author, thanks for your code. I have a question about evaluating RelTR on PredCLS/SGCLS , wondering how to assign the ground truth information to the matched triplet proposals?Thanks a lot.

**Comment by yrcong** [comment]
Hi, 
i assigned the gt information (bboxes and classes) with the matched id. For example in the ground truth there are 10 relationships. After the matching 10 triplet proposals are selected. The relationship prediction is directly used while the predicted bboxes and classes are replaced by the GT
