### ISSUE TITLE
The problem of RelTR Demo.ipynb

### ISSUE THREAD

**Issue by rourou-droid** [yrcong/RelTR#30]
![1690274826716](https://github.com/yrcong/RelTR/assets/140496124/0180f34a-f98a-4e16-8460-272d21d8a88e)
I would like to ask you a question. When I run the RelTR Demo.ipynb you published, I encountered the error as shown in fig. Also, many tensors in conv_features are zeros. Could you guide me on how to resolve this?

**Comment by yrcong** [comment]
It seems there is no confident triplet. You can downgrade the confident threshold and get more output proposals:)
