### ISSUE TITLE
about output 

### ISSUE THREAD

**Issue by zhujiaxiao** [yrcong/RelTR#31]
I see that in the literature, the Scene graph is finally generated, but the output of the open source code is only the attention heatmap and the identification results on the image, right? Is there any way to generate the final integrated Scene graph?

**Comment by lalalisa666** [comment]
> I see that in the literature, the Scene graph is finally generated, but the output of the open source code is only the attention heatmap and the identification results on the image, right? Is there any way to generate the final integrated Scene graph?

hi, have you solved this problem?

**Comment by yrcong** [comment]
That's quite an issue! As I know, people can draw scene graphs automatically with Graphviz. Please check https://github.com/ranjaykrishna/GraphViz

However, scene graphs in the papers are usually drawn by humans...
