### ISSUE TITLE
About training strategy

### ISSUE THREAD

**Issue by Vincent-luo** [yrcong/RelTR#36]
Hi, I'm now training the reltr model on VG dataset and I find the training time is quite long. It takes ~2.5 days to train for 150 epochs on 4*3090 with batchsize 4. Im not sure whether I'm doing something wrong or it does need much time to train from scratch. 

And I want to ask if you have tried other training strategies like multiple stage. For example, in the first stage just train the model for object detection, the in the second stage only train the triplet decoder and freeze the encoder and entity decoder(or updating with a low leaning rate). That sounds more practical and will reduce the training time in theory.

**Comment by yrcong** [comment]
Hi, 
We didn't do it since the end-to-end training is our objective. But the multiple-stage training sounds reasonable in practice.

You can even try to load the pretrained DETR.
