### ISSUE TITLE
Some questions about evaluation

### ISSUE THREAD

**Issue by xhonghu** [yrcong/RelTR#38]
Hello,
Firstly, I want to express my gratitude for sharing your code. It has been incredibly helpful to me. 

I see such  evaluation results in your paper

![eval](https://github.com/yrcong/RelTR/assets/103254694/b8a34802-b3df-48ee-b93d-f099278cbe3d)

How did you get your SGDet, SGCls, PredCls evaluation results?

After running the evaluation in your code, I can't find a correspondence。

![eval2](https://github.com/yrcong/RelTR/assets/103254694/008cb784-5874-4cfd-bd35-9acc57ac0bab)

Could you please give me some code about it or explain the results of your evaluation results?

I'm looking forward to your response.

**Comment by yrcong** [comment]
Hi, 
what you showed now is the evaluation results of object detection. Did you evaluate with the command:
`python main.py --dataset vg --img_folder data/vg/images/ --ann_path data/vg/ --eval --batch_size 1 --resume ckpt/checkpoint0149.pth`

**Comment by 121546hhx** [comment]
Thank you very much for your reply! Analyze the results of  your eval code, i get the sdget result.   but SGCls, PredCls I can't find.

**Comment by Gezelligheid-debug** [comment]
> Hello, Firstly, I want to express my gratitude for sharing your code. It has been incredibly helpful to me.
> 
> I see such evaluation results in your paper
> 
> ![eval](https://private-user-images.githubusercontent.com/103254694/281302692-b8a34802-b3df-48ee-b93d-f099278cbe3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzY4MDksIm5iZiI6MTcwNjI3NjUwOSwicGF0aCI6Ii8xMDMyNTQ2OTQvMjgxMzAyNjkyLWI4YTM0ODAyLWIzZGYtNDhlZS1iOTNkLWYwOTkyNzhjYmUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzQxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjE0MWJmN2MxZWNkYWFkZGU0ZjgxODUxOWZiODg4YzVmNGNjOTJhOGY2Y2NmYjM3ZDU0ZWQ4ZTllMTI5MjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ijEgQoRmTFTlcUnIywWf14jDPkNcuftdgb4Var_KvYI)
> 
> How did you get your SGDet, SGCls, PredCls evaluation results?
> 
> After running the evaluation in your code, I can't find a correspondence。
> 
> ![eval2](https://private-user-images.githubusercontent.com/103254694/281312250-008cb784-5874-4cfd-bd35-9acc57ac0bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzY4MDksIm5iZiI6MTcwNjI3NjUwOSwicGF0aCI6Ii8xMDMyNTQ2OTQvMjgxMzEyMjUwLTAwOGNiNzg0LTU4NzQtNGNmZC1iZDM1LTlhY2M1N2FjMGJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxMzQxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJkYjY2YWI1N2VlNzBmNDdiYmNmN2NiY2NkZjVjYTdhZjM1ZTcwNTgwNTg4MTdhOGQ1ZThkNmEwZWFiYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qHui25SM7kg5-0LuV7l3oSOqtBoILvj-oTV6vIQBkh4)
> 
> Could you please give me some code about it or explain the results of your evaluation results?
> 
> I'm looking forward to your response.

I have also shown the results in your photos. Has your problem been resolved? Should the recall rate be just a few tenths?
