### ISSUE TITLE
ImportError: cannot import name '_new_empty_tensor'

### ISSUE THREAD

**Issue by CurtisDeCastro** [yrcong/RelTR#4]
Getting this error when trying to run inference.py-- is this related to version issues with python/conda? Did my best to triage the issue independently, but all I could find is that this is a known issue with pytorch that was fixed with python 3.6, however that is the version I'm running. 

Appreciate you for all your work on this btw!

**Comment by yrcong** [comment]
Which pytorch version did you use? Could you provide more information like the error log?

**Comment by linhuixiao** [comment]
I successfully reproduced by following the author's description. maybe your numpy version not match or some environment problem.
