### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dadawdadD** [yrcong/RelTR#53]

**Comment by yrcong** [comment]
For object annotations we follow the COCO format. The relationships are formulated as a list of triplets <subject_box_index, object_box_index, relation_class_index>.

**Comment by dadawdadD** [comment]
Thank you for your reply！

**Comment by dadawdadD** [comment]
Is there any tool to make this kind of dataset? Looking forward to your reply！

**Comment by yrcong** [comment]
If you want to annotate data by yourself, labelbox is an option (I didn't try it)

**Comment by dadawdadD** [comment]
Thank you for your reply, I will try if this is feasible
