### ISSUE TITLE
Incompatible tensor size when a running a batch size of 2 

### ISSUE THREAD

**Issue by ikram-md** [yrcong/RelTR#56]
I successfully managed to solve the environment issue, yet now when i tried to launch the training, i am obtaining the following error : 
![image](https://github.com/yrcong/RelTR/assets/56800980/99c3054e-9c4b-4d4b-8b79-451c7dd5e029)
And when i use batch size of 1 i get the following error : 
![image](https://github.com/yrcong/RelTR/assets/56800980/25950397-e5aa-458c-b738-11915422e57f)

**Comment by ikram-md** [comment]
For now i cannot use a greater batch size than 1, and when using a `batch_size 1` other issues are provoked.

**Comment by yrcong** [comment]
Please check if you have changed the dataset code. 

For the first error (Image 1), it seems you do not pad the images in the same size so that they can be concatenated.

For the second error (Image 2), definitely something wrong with the dataset or collate function. t should be a dict.
