### ISSUE TITLE
Will RelTR support Resnet101 as backbone and provided a trained checkpoint with Resnet101 as backbone?

### ISSUE THREAD

**Issue by linhuixiao** [yrcong/RelTR#8]
Will RelTR support Resnet101 as backbone and provided a trained checkpoint with Resnet101 as backbone?

**Comment by yrcong** [comment]
Regardless of GPU memory, ResNet101 can be used definitely.
You can directly use the pretrained ResNet101 provided by Pytorch, as we used Res50.
